---
title: "Assignment 1: Simple Modelling"
date: 2026-09-11
due: "September 25, 2026"
---

Due date: {{< meta due >}} at 5 pm. This is a Friday; I will not be collecting submissions until the following Monday, so use that information as you wish. Reasonable requests for extensions will likely be granted, provided I see some evidence of progress prior to the due date.

## Setup
You may work in groups up to 3. Please join a group on D2L, then pick **one person** to [accept the assignment](https://classroom50.org/mru-data3464-f26/data-3464/assignments/assignment-1/accept) and create the GitHub repository with the dataset. Whoever does this becomes the group manager and can invite team members with their GitHub username.

::: {.callout-tip title="If you make a mistake with groups"}
Don't worry, this is the first time for all of us using Classroom50, and the platform itself is brand new. Let me know if you accidentally created two groups, or joined the wrong one; I can modify groups on the backend.
:::

In your repo, you may store as many python files, Jupyter notebooks, draft documents, etc. However, please create **one coherent report named assignment1** that includes:
- Your group members' names
- Some key figures and commentary on data exploration
- Description of your data processing decisions
- A summary of your experiments
- Figures and discussion on your final models

Your report can be in Markdown or PDF format. In these instructions, I've indicated where you should write **in your report** in an annoying bold face.

I encourage you to talk things through as you try different things. If you talk with classmates from a different group, **cite their contribution**. Similarly, if you use a web resource, add a link in the code — this is both polite, and a good habit to develop.

## The problem
You are working for the provincial government and are asked to help predict staffing budgets. Salaries are considered a known quantity, but benefits (cash and non-cash) appear to be more variable. To address this, you must build two models:
- a regression model to predict the total cash and non-cash benefits per employee
- a classification model to identify employees with less than $20,000 in benefits[^1]

[^1]  Why under $20k? I don't know, maybe they get a prize or something. It just seemed like a clear dividing line when I inspected the data, and I needed an excuse to turn this into a classification problem.

The `benefits_train.csv` file in your starter repo has been created from the [Alberta Salary and severance disclosure table](https://www.alberta.ca/salary-and-severance-disclosure-table); I have reserved a separate test set and will release it for your testing pleasure after the assignment is complete.

### Preliminary EDA and processing
Exploratory data analysis is an important step in data processing, but it is not the main focus of this assignment. You will need to do just enough to have an understanding of what the data looks like, such as:
- What features are present
- Are there any obvious relationships between features
- How many unique values (categorical) or what are the distributions (numeric)

The results of your EDA will inform your processing pipeline, such as choosing a categorical encoding approach.

**In your report**, include a key figure or two from your EDA and briefly describe what you see.

### Regression model
Using your choice of [regression model](https://scikit-learn.org/stable/supervised_learning.html) from Scikit-learn, create and train a regression model to predict the **total benefits** (`NonCashBenefits + CashBenefits`) for each employee. You will need to create this total benefits column, or as a separate vector.

::: {.callout-tip}
Don't forget to remove or exclude the `CashBenefits` and `NonCashBenefits` fields of your training dataframe!
:::

1. You will need to do some basic processing on the training data, but don't feel the need to use all the features! **In your report**, briefly justify the following decisions:

    - Which features should be included?
    - How should categorical features be encoded?
    - How should numeric features be transformed?

    I recommend creating a Scikit-learn [`Pipeline`](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html) to be able to `fit` your processing parameters and model all in one go.

2. Validate your model using cross-validation. An easy way to do this is with [`sklearn.model_selection.cross_val_score`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html). You will need to choose an appropriate metric and pass it as the `scoring` parameter; feel free to experiment with multiple. **In your report**, briefly justify why the metric chosen was appropriate.

3. Iterate! Based on the results of cross-validation, try to improve your model. You can tweak your processing parameters, model parameters, or even choose a different model. Briefly document your experiments **in your report**, making note of any changes that have impact.
   > Don't spend *too* much time refining your model — the goal is to learn about the process and the factors that impact the results, not to produce the absolute best predictive model possible.

4. When you're happy with the results, document your final pipeline **in your report**. This can just be a copy/paste of your pipeline construction code.

At this stage, you don't have final test data, so the process basically stops here.

### Classification model
This time, you'll be doing basically the same thing, but with a binary classification model. Create your prediction target (labels) as a Boolean vector by thresholding total benefits < 20,000. This can be done in numpy simply as (for example):

```python
y = total_benefits < 20_000
```

1. Count how many labels you have of each class (`True` or `False`). **In your report**, comment on the class balance.

2. As before, create a Scikit-learn pipeline and pick a classification model. You may copy the same pipeline from the previous task and simply swap out the model; you don't need to document your processing decisions again.

3. Once more, pick an appropriate metric and validate your model using cross-validation. Be careful of the class (im)balance!

4. Again, iterate and try to improve your model based on the results of cross-validation. **In your report**, make note of what you try and how it impacts the model.

4. When you're happy with the results, document your final pipeline **in your report**. This can just be a copy/paste of your pipeline construction code, formatted neatly as a code block.

## Reflections
Write a brief paragraph describing what you found challenging about this assignment, and one thing that was particularly interesting or surprising.

## Marking Scheme
Each of the following components will be marked on a 4-point scale and weighted.

| Component                                                           | Weight |
| ------------------------------------------------------------------- | ------ |
| Preliminary EDA                                                     | 10%    |
| Regression pipeline development process, observations, comments     | 30%    |
| Classification pipeline development process, observations, comments | 30%    |
| Reflections                                                         | 20%    |
| Citations, overall coherency                                        | 10%    |

<br />

| Score | Description                                                            |
| ----- | ---------------------------------------------------------------------- |
| 4     | Excellent — thoughtful and creative without any errors or omissions    |
| 3     | Pretty good, but with minor errors or omissions                        |
| 2     | Mostly complete, but with major errors or omissions, lacking in detail |
| 1     | A minimal effort was made, incomplete or incorrect                     |
| 0     | No effort was made, or the submission is plagiarized                   |