---
config:
  themeVariables:
    fontSize: 20px
---

flowchart LR
    A[Tabular data] --> B[Split]
    B --> B2[EDA]
    subgraph Repeat until happy
        B2 --> C[Categorical\nEncoding]
        B2 --> D[Numerical\nTransformations]
        C --> E[Model]
        D --> E[Model]
        E --> F[Validate]
    end
    F --> G[Final\nModel]